identifier: "<%= p("gremlin.identifier").to_s.empty? ? "#{@spec.name}-#{@spec.id}" : p("gremlin.identifier") %>"

team_id: <%= p("gremlin.team_id") %>

<% if_p("gremlin.service_url") do %>
service_url: "<%= p("gremlin.service_url") %>"
<% end %>
  
<% if_p("gremlin.ssl_cert_file") do %>
ssl_cert_file: |
<%= p("gremlin.ssl_cert_file").to_s.gsub(/^/, "  ") %>
<% end %>

<% if_p("gremlin.team_secret") do %>
team_secret: <%= p("gremlin.team_secret") %>
<% end.else do %>
team_certificate: |
<%= p("gremlin.team_certificate").to_s.gsub(/^/, "  ") %>

team_private_key: |
<%= p("gremlin.team_private_key").to_s.gsub(/^/, "  ") %>
<% end %>

<% if_p("gremlin.https_proxy") do %>
https_proxy: "<%= p("gremlin.https_proxy") %>"
<% end %>


push_metrics:      <%= p("gremlin.push_metrics") %>
collect_processes: <%= p("gremlin.collect_processes") %>
collect_dns:       <%= p("gremlin.collect_dns") %>

<% if_p("gremlin.iam_role") do %>
iam_role: <%= p("gremlin.iam_role") %>
<% end %>


